# PHYS 3120 - Prof. Wise // Basic Programming (Chapter 2)
## If-statements and while loops (Section 2.3)

* Perhaps the most different python syntax is how programming blocks are delineated.
* Blocks are separated by **indentation**
* Most other languages use a begin/end or open/close braces `{}`

### If-statements

* Below is an example of an if-statement with the appropriate indentation.
* Langauge-aware editors will insert enough spaces for the indentation when you hit TAB.

In [1]:
x = ''
while not x.isnumeric():
    x = input("Enter a number: ")
    print(x, type(x), x.isnumeric())
    if not x.isnumeric():
        print("You didn't enter a number!")
x = float(x)
if x > 5:
    print("I'm greater than 5.  x = %f" % (x))
elif x < 2:
    print("I'm less than 2. x = %f" % (x))
else:
    print("I'm less than or equal to 5. x = %f" % (x))

Enter a number:  1


1 <class 'str'> True
I'm less than 2. x = 1.000000


2 <class 'str'> True
I'm less than or equal to 5. x = 2.000000


* Jupyter will automatically indent for you.
* If you want to close the block, just hit backspace and it will return to the "parent" programming block.

* There are several comparison operators for numbers.
* `==`, `!=`, `>`, `>=`, `<`, `<=`

In [2]:
string = 'str'
if string.startswith('s'):
    print('here')

here


In [3]:
help(string)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to 'utf-8'.
 |  errors defaults to 'strict'.
 |
 |  Methods defined here:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, v

### While-loops and break/continue statements

* `while`-loops continue until some criteria is met, usually a comparison
* Loop blocks are distinugished by indentation, just like if-statements
* `break` statements will immediate exit any type of loop
* `continue` statements will skip the rest of the loop and continue to the next iteration

In [4]:
from numpy import random
x = 1.0
while x < 10:
    xold = x
    rand_number = random.random()  # random number between 0 and 1
    x *= (1+rand_number)
    print("x = %f -> %f (rand_number = %f)" % (xold, x, rand_number))
    if rand_number < 0.1:
        break

x = 1.000000 -> 1.700883 (rand_number = 0.700883)
x = 1.700883 -> 3.353208 (rand_number = 0.971452)
x = 3.353208 -> 5.505231 (rand_number = 0.641780)
x = 5.505231 -> 6.270786 (rand_number = 0.139060)
x = 6.270786 -> 11.792350 (rand_number = 0.880522)


Here is an example of a break and continue statement, used with an infinite loop.
* _Note:_ Boolean types in python are just `True` and `False` (capitalized!)
* `isinstance` checks whether a variable is a particular type.

In [5]:
while True:
    inp = input("Enter something (-1 to exit): ")
    try:
        inp = float(inp)
    except:
        inp = inp
    if isinstance(inp, str):
        print("You entered a string: %s" % (inp))
        print("Not doing any calculation.")
        continue
    inp = float(inp)
    if inp == -1:
        break
    # ......
    # Imagine there are many calculations here
    # An else-statement would be unwieldy
    # ......
    inp = inp**0.5
    print("The square root of your entry is %s" % (inp))

Enter something (-1 to exit):  -1


In [6]:
x = 1
if x == 1: print('here')
else: print('not')

here


## Containers: Tuples, Lists, Arrays, and Dictionaries (Section 2.4)
### Tuples
* Tuples are denoted by parentheses and **cannot be modified**.  Usually they can be used as parameters, not changable variables.
* Elements of a tuple are accessed by the [] operator.
* Remember that python is 0-based (like C++, but not Java)

In [7]:
tup = (5,1,8,3,8,'a',True)
print(tup)
print(tup[6])

(5, 1, 8, 3, 8, 'a', True)
True


There are only two methods associated with searching a tuple.
* `index`: returns the element number of the first instance of the argument
* `count`: returns hold many instances of the argument

In [8]:
print(tup.index(8))
print(tup.count(8))
print(tup.count(5))

2
2
1


In [9]:
print(len(tup))

7


In [10]:
for i in tup:
    print(i*2)

10
2
16
6
16
aa
2


In [11]:
print(72*"-")

------------------------------------------------------------------------


In [12]:
tup[1] = 1

TypeError: 'tuple' object does not support item assignment

### Lists
* Lists are much more useful in python, as their elements can be modified, and they can shortened or lengthened.
* List elements may have different variable types.  For example, a list can contain an integer, string, and complex number.

In [13]:
multitype = [1, 2.0, '3.00']
print(multitype)

[1, 2.0, '3.00']


Here are two examples of adding to and removing from a list with the `append` and `remove` methods.

In [14]:
test_list = [1,3,5,7,9,5,11]
print(test_list)
test_list.append(13)
print(test_list)
test_list.remove(5)
print(test_list)

[1, 3, 5, 7, 9, 5, 11]
[1, 3, 5, 7, 9, 5, 11, 13]
[1, 3, 7, 9, 5, 11, 13]


One can determine a length of a list or tuple with the method `len()`

In [15]:
print("The tuple %s has %d elements" % (tup, len(tup)))
print("len(test_list) = %d" % (len(test_list)))

The tuple (5, 1, 8, 3, 8, 'a', True) has 7 elements
len(test_list) = 7


We can also sort a list in-place.

In [16]:
list_to_sort = [38,-1,12,-18,12.3]
list_to_sort.sort()
print(list_to_sort)

[-18, -1, 12, 12.3, 38]


In [17]:
multitype.sort()  # Doesn't work for multitype lists

TypeError: '<' not supported between instances of 'str' and 'float'

* Lists are good (but arrays are better, we'll cover those next) for vectors.
* Suppose if we have a particle at the coordinate x,y,z, stored in individual variables.
* We can create a list from those variables.

In [18]:
x = 0.12
y = 0.83
z = 0.53
r = [x, y, z]
print(r)
print(3*r)
print(3*[0.0])

[0.12, 0.83, 0.53]
[0.12, 0.83, 0.53, 0.12, 0.83, 0.53, 0.12, 0.83, 0.53]
[0.0, 0.0, 0.0]


* There are several methods associated with lists for searching, sorting, and modifying.
* *Only the method names are important, but if you're curious, I used some short-hand notation for looping, which haven't covered yet, to remove the private methods.*

In [19]:
dir(r)

['__add__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [20]:
print([d for d in dir(r) if not d.startswith('__')])

['append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


### Arrays (Section 2.4.2)
* Arrays are like lists but are ordered and contain a single type
* They can be multi-dimensional
* They are part of the `numpy` package
* Array operations are possible and much faster than loops
* Let's create two arrays: a 1D array with increasing numbers and 2D array with twos.
* By default, arrays contain floats

In [21]:
import numpy as np
one_d = np.arange(3)
two_d = 2 * np.arange(9).reshape((3,3))  # 3x3 matrix
print('one_d = %s' % (one_d))
print('inter = %s' % (2*np.arange(9)))
print('two_d = %s' % (two_d))

one_d = [0 1 2]
inter = [ 0  2  4  6  8 10 12 14 16]
two_d = [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


One can select a single element out of the array

In [22]:
a = one_d[1]
b = two_d[1,1]
print(a, b)

1 8


Or one can "slice" an array, obtaining multiple elements

In [23]:
print(one_d[0:2]) # includes 0,1 elements, but not 3rd (2) element
print(two_d[:,0]) # the first column

[0 1]
[ 0  6 12]


Arrays can be used in arithmetic operations.

In [24]:
c = 5*one_d
print(c)

[ 0  5 10]


In [25]:
d = one_d * two_d
print(d)  # multiplying columns by each element in one_d
print(np.dot(one_d,two_d))  # matrix mult

[[ 0  2  8]
 [ 0  8 20]
 [ 0 14 32]]
[30 36 42]


In [26]:
print(np.sqrt(d))

[[0.         1.41421356 2.82842712]
 [0.         2.82842712 4.47213595]
 [0.         3.74165739 5.65685425]]


Lastly, we can specify the variable type of the array in the second argument.

In [27]:
int_array = np.random.random((3,3))
print(int_array)

[[0.24793835 0.00892699 0.45088138]
 [0.6269875  0.37991287 0.84070117]
 [0.85101026 0.53293303 0.78465436]]


In [28]:
int_array += 259
print(int_array)

[[259.24793835 259.00892699 259.45088138]
 [259.6269875  259.37991287 259.84070117]
 [259.85101026 259.53293303 259.78465436]]


In [29]:
print(int_array[0,:], '1st row')
print(int_array[:,0], '1st col')

[259.24793835 259.00892699 259.45088138] 1st row
[259.24793835 259.6269875  259.85101026] 1st col


In [30]:
col = np.ones((3,1))
print(col)
row = np.ones((1,3))
print(row)

[[1.]
 [1.]
 [1.]]
[[1. 1. 1.]]


### Reading from text files (Section 2.4.3)
* `numpy` has the routine `loadtxt()` that easily reads plain text files and puts the values into an array
* Suppose that we have a file called `03_values.txt` with the following contents.

```
112.3 182
18.2 1283
38 3.3
39 1
```

In [31]:
file_numbers = np.loadtxt('03_values.txt')
print(file_numbers)

[[1.123e+02 1.820e+02]
 [1.820e+01 1.283e+03]
 [3.800e+01 3.300e+00]
 [3.900e+01 1.000e+00]]


In [32]:
x = file_numbers[:,0]
y = file_numbers[:,1]

In [33]:
print(x)
print(y)

[112.3  18.2  38.   39. ]
[1.820e+02 1.283e+03 3.300e+00 1.000e+00]


* Arrays have many methods and attributes that can tell you about their contents and structure.
* `size` and `shape` are useful ones

In [34]:
print('Number of elements: %s' % (file_numbers.size))
print('Matrix shape: %s' % (file_numbers.shape,))  # the extra comma is necessary when formatting a tuple
print(file_numbers.shape)  # Otherwise, one can just print it.

Number of elements: 8
Matrix shape: (4, 2)
(4, 2)


In [35]:
print([d for d in dir(file_numbers) if not d.startswith('__')])

['T', 'all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'base', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'ctypes', 'cumprod', 'cumsum', 'data', 'device', 'diagonal', 'dot', 'dtype', 'dump', 'dumps', 'fill', 'flags', 'flat', 'flatten', 'getfield', 'imag', 'item', 'itemset', 'itemsize', 'mT', 'max', 'mean', 'min', 'nbytes', 'ndim', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'real', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'shape', 'size', 'sort', 'squeeze', 'std', 'strides', 'sum', 'swapaxes', 'take', 'to_device', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


Above are all of the methods associated with an array.  Suppose that we want to find the maximum value and mean value.

In [36]:
max_value = file_numbers.max()
mean_value = file_numbers.mean()
print(max_value, mean_value)

1283.0 209.6


* Matrix operations are also possible.  What if we wanted to calculate the following operation.

\begin{equation}
\begin{pmatrix} 1 & 3\\ 2 & 4 \end{pmatrix}
\begin{pmatrix} 4 & -2\\ -3 & 1 \end{pmatrix}
+ 2 \begin{pmatrix} 1 & 2\\ 2 & 1 \end{pmatrix}
\end{equation}

* In python, we would calculate it as the following.
* `array()` converts lists into arrays.
* `dot()` is the dot product if the arrays are 1D or matrix multiplication if they are 2D

\begin{equation}
\left[
\begin{array}{cccc|c}
1 & 0 & 3 & -1 & 0 \\
0 & 1 & 1 & -1 & 0 \\
0 & 0 & 0 & 0 & 0 \\
\end{array}
\right]
\end{equation}

In [37]:
a = np.array([[1,  3], [2, 4]], 'int')
b = np.array([[4, -2], [3, -1]], 'int')
c = np.array([[1,  2], [2, 1]], 'int')
d = np.dot(a,b) + 2*c
print(d)

[[15 -1]
 [24 -6]]


### Example: Geometric mean
* The geometric mean is defined to be the $n^{\rm th}$ root of their product.

\begin{equation}
\bar{x} = \left[ \prod_{i=1}^n x_i \right]^{1/n}
\end{equation}

* We can calculate this in one line with `numpy` methods, specifically `product()`.

In [38]:
n = file_numbers.size
geo_mean = np.prod(file_numbers)**(1./n)
print(geo_mean)

35.15717060982651


* However for very large arrays, we have to worry about floating point overflows, that is, numbers too large to be represented by a float variable, which is $2^{127} = 1.7 \times 10^{38}$ for 32-bit floats and $2^{1023} = 1.8 \times 10^{308}$ for 64-bit floats, which is the default in python.
* To avoid this in a geometric mean, we can re-arrange the equation.
* First, we take the natural log of both sides,

\begin{equation}
\ln \bar{x} = \frac{1}{n} \sum_{i=1}^n \ln x_i
\end{equation}

* Then, we can take the exponential of both sides to recover the geometric mean.

\begin{equation}
\bar{x} = \exp\left( \frac{1}{n} \sum_{i=1}^n \ln x_i \right)
\end{equation}

* The sum of natural logarithms will be less likely to overflow a float variable.
* Coding this up, we can still calculate the geometric mean in one line, using `numpy` methods.

In [39]:
geo_mean = np.exp(np.sum(np.log(file_numbers)) / n)
print(geo_mean)

35.15717060982651


#### Warning
* When copying an array to another variable, `b = a` is not sufficient.
* The array `b` is a reference to the array `a`.
* Any operation done to `a` will be reflected in `b`.

In [40]:
a = np.array([1,2,3])
b = a
print('Before: ', a, b)
a[1] = 42
print('After: ', a, b)

Before:  [1 2 3] [1 2 3]
After:  [ 1 42  3] [ 1 42  3]


* To make a copy of an array, we must use the `copy()` function in `numpy`.

In [41]:
a = np.array([1,2,3])
b = a.copy()
print('Before: ', a, b)
a[1] = 42
print('After: ', a, b)

Before:  [1 2 3] [1 2 3]
After:  [ 1 42  3] [1 2 3]


### Dictionaries (Not in the book)
* Dictionaries are just like the `struct` variables in C++
* They contain variables of different type
* Elements are referenced by a string, integer, or float
* It's usually best practice to avoid floats as references (known as keys) because of precision issues
* In practice, I find them the most usefuls for storing parameters in calculations
* They can be defined in the two following manners

In [42]:
dict1 = dict(one=1, two=2, three=3)
dict2 = {'one': 1, 'two': 2, 3: 3}
print('dict1 = %s' % (dict1))
print('dict2 = %s' % (dict2))
print('dict1 == dict2? %s' % (dict1 == dict2))

dict1 = {'one': 1, 'two': 2, 'three': 3}
dict2 = {'one': 1, 'two': 2, 3: 3}
dict1 == dict2? False


* Notice that they are not in the order in which we assigned them.
* We can inspect the keys with the `keys()` method

In [43]:
print(dict1.keys())

dict_keys(['one', 'two', 'three'])


* We can access and modify individual elements of the dictionary
* We can also add new elements to the dictionary

In [44]:
print(dict1['one'])
dict1['one'] *= -1
print(dict1)

1
{'one': -1, 'two': 2, 'three': 3}


In [45]:
dict1[4] = -44
dict1[10] = 'str'
print(dict1)

{'one': -1, 'two': 2, 'three': 3, 4: -44, 10: 'str'}


Dictionaries have the following methods, which you can look up their meanings in the built-in help.

In [46]:
print([d for d in dir(dict1) if not d.startswith('__')])

['clear', 'copy', 'fromkeys', 'get', 'items', 'keys', 'pop', 'popitem', 'setdefault', 'update', 'values']


## Ending point: 08 January 2025

## For-loops (Section 2.5)
* for-loops are much more common in programming than while-loops
* In python, they loop over what's called an iterator
* For our purposes, this is usually a list
* The most basic for-loop that's taught in programming classes use a counter variable.  For example in C++

```c++
for (i = 0; i < 3; i++) {
    a = i*i;
}
```

* And in Matlab,

```matlab
for i = 0:3
    a = i*i;
end
```

* In python, we can use the `range()` function that gives you a list of integers.
    * If given 1 argument n, it will return a list from 0 to n-1.
    * If given 2 arguments m and n, it will return a list from m to n-1.
    * If given 3 arguments m, n, and k, it will return a list from m to n-1 for every $k^{th}$ integer

In [47]:
for i in range(3):
    print(i*i)

0
1
4


In [48]:
print([i for i in range(5)])
print([i for i in range(5,10)])
print([i for i in range(5,10,2)])
print([i for i in range(10,5,-1)])

print([2*i for i in range(5)])

[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[5, 7, 9]
[10, 9, 8, 7, 6]
[0, 2, 4, 6, 8]


Using `range()` as an iterator in the loop, we get

In [49]:
for i in range(5,10):
    print(i, i**2)

5 25
6 36
7 49
8 64
9 81


When looping through a list, it's usually useful to have a counter variable to indicate which element we are inspecting.  We could do the following.

In [50]:
a = [5,1,23,43]
b = [12,4,13,1]
i = 0
for el in a:
    print("The square of the %d-th element of a is %d" % (i, el**2))
    print("The %d-th element of b is %d" % (i, b[i]))
    print("")
    i += 1

The square of the 0-th element of a is 25
The 0-th element of b is 12

The square of the 1-th element of a is 1
The 1-th element of b is 4

The square of the 2-th element of a is 529
The 2-th element of b is 13

The square of the 3-th element of a is 1849
The 3-th element of b is 1



But python has the handy `enumerate()` method that returns a counter variable and the element of the iterator.

In [51]:
for i, el in enumerate(a):
    print(i, el)

0 5
1 1
2 23
3 43


In [52]:
a = [1, 2, 3]
b = [6,7,8]
for ia, aa in enumerate(a):
    for ib, bb in enumerate(b):
        print(ia, ib, aa, bb)

0 0 1 6
0 1 1 7
0 2 1 8
1 0 2 6
1 1 2 7
1 2 2 8
2 0 3 6
2 1 3 7
2 2 3 8


What if we want to loop through a sorted copy of the list?  We can use the `sorted()` method, which doesn't sort the list in-place, but just returns a sorted copy.

In [53]:
asort = sorted(a)

In [54]:
print(asort)

[1, 2, 3]


In [55]:
a[1] = -10

In [57]:
print(a)
print(asort)

[1, -10, 3]
[1, 2, 3]


In [58]:
for i, el in enumerate(sorted(a)):
    print(i, el)

0 -10
1 1
2 3


* We can also loop through dictionaries.
* By default, python loops through only their keys.

In [59]:
for key in dict1:
    print(key, dict1[key])

one -1
two 2
three 3
4 -44
10 str


This is fine.  But we can use the dictionary method `items()` to return *both* the key and value.

In [60]:
for key, value in dict1.items():
    print(key, value)

one -1
two 2
three 3
4 -44
10 str


We can also loop through a sorted list of the dictionary's keys.

In [61]:
trash = dict1.pop(4)
trash = dict1.pop(10)

In [62]:
for key, value in sorted(dict1.items()):
    print(key, value)

one -1
three 3
two 2


In [63]:
dict1[4] = 419
dict1[10] = 1982

In [64]:
dict1a = {} # empty dictionary
for key, value in dict1.items():
    if isinstance(key, str):
        dict1a[key] = value
for key, value in sorted(dict1a.items()):
    print(key, value)

one -1
three 3
two 2


* **For math operations, LOOPS ARE BAD in python.**  They will always be slower than direct array arithmetic. (Note this is not the case for C++ or other compiled languages.)
* Suppose if we want to create an array with cubes up to 10.
* `arange()` is the same as the built-in `range()` method, but returns an array instead of a list

In [65]:
# Looping (bad)
N = 10
a = np.arange(1,N+1)
b = np.zeros(N)
for i, num in enumerate(a):
    b[i] = num**3.0
print(b)

[   1.    8.   27.   64.  125.  216.  343.  512.  729. 1000.]


In [66]:
# Array arithmetic (good)
b = a**3.0
print(b)

[   1.    8.   27.   64.  125.  216.  343.  512.  729. 1000.]


* This is a simple example, but the speed increases become more apparent for large operations.
* Let's time it, taking a list of 100,000 numbers to the 5/2 power

In [68]:
import time

N = 10000000
a = np.arange(1,N+1)
b = np.zeros(N)

start = time.time()
for i, num in enumerate(a):
    b[i] = num**2.5
end = time.time()
looptime = end-start
print("Looping took %f seconds" % (looptime))


start = time.time()
b = a**2.5
end = time.time()
print("One array operation took %f seconds (%.1fx speedup)" % (end-start, looptime/(end-start)))

Looping took 9.800606 seconds
One array operation took 0.060229 seconds (162.7x speedup)


## User-defined function (Section 2.6)
* As with any programming language, we can define functions and routines.
* Programming blocks inside functions are delineated by indentation, just like if-statements and loops.
* Below is an example of a factorial function.

In [69]:
def factorial(n):
    f = 1.0
    for k in range(1,n+1):
        f *= k
    return f

In [70]:
fivebang = factorial(5)
print(fivebang)

120.0


* Functions can also accept multiple arguments with default values, and they can return multiple values or an array.
* Suppose if we have some spherical coordinates in the xy-plane that we want to convert into Cartesian coordinates.
* The function below has the default value for phi as $\pi/2$ if it's not given.

In [71]:
import numpy as np
def cartesian(r, theta, phi=np.pi/2):
    x = r * np.cos(theta) * np.sin(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(phi)
    return x, y, z

r = 2
theta = 0.5  # radians
xyz = cartesian(r, theta, np.pi/12)
print(xyz)
x, y, z = cartesian(r, theta)
print(x, y, z)

(np.float64(0.4542701613341802), np.float64(0.24816892019860304), np.float64(1.9318516525781366))
1.7551651237807455 0.958851077208406 1.2246467991473532e-16


* We can also give the user the option to return a list or an array with an array being the default

In [72]:
def cartesian(r, theta, phi=np.pi/2, array=True):
    x = r * np.cos(theta) * np.sin(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(phi)
    if array:
        return np.array([x, y, z])
    else:
        return x, y, z

position = cartesian(r, theta, array=True)
print(position)

[1.75516512e+00 9.58851077e-01 1.22464680e-16]


Then if we want, we can calculate its norm, which is $r$.

In [73]:
norm = np.sqrt((position**2).sum())
print(norm)

2.0


## Good programming style (Section 2.7)
1. Include comments in your programs (or markdown in notebooks)
2. Use meaningful variable names
3. Use the right types of variables
4. Import functions and modules first
5. Give your constants names
6. Employ user-defined functions and modularity, where appropriate
7. Print out partial results and updates throughout your program
8. Lay out your programs clearly.
9. Don't make your programs unnecessarily complicated.

Remember that good programming, like good science, is a matter of creativity as well as technical skill.  Computers are a tool that are mallable to a programmer's needs.

In [ ]:
h = input('Enter height(m):')